# Example: How to configure BSR authentication for ProtoDiff

# Step 1: Get your BSR token from https://buf.build/settings/user
# Step 2: Create a Kubernetes Secret with your token

---
apiVersion: v1
kind: Secret
metadata:
  name: bsr-token
  namespace: protodiff-system
type: Opaque
stringData:
  # Replace with your actual BSR token from https://buf.build/settings/user
  token: "your-bsr-token-here"

---
# Step 3: Update the ProtoDiff Deployment to use the secret
# Apply this patch or edit deploy/k8s/install.yaml directly

# Add to the deployment spec.template.spec.containers[0]:
#
# env:
#   - name: BSR_TOKEN
#     valueFrom:
#       secretKeyRef:
#         name: bsr-token
#         key: token
#
# Example full deployment snippet:
#
# spec:
#   template:
#     spec:
#       containers:
#       - name: protodiff
#         image: protodiff:latest
#         env:
#         - name: BSR_TOKEN
#           valueFrom:
#             secretKeyRef:
#               name: bsr-token
#               key: token
#         - name: USE_MOCK_BSR
#           value: "false"  # Use real BSR client

---
# Alternative: Create secret from command line
#
# kubectl create secret generic bsr-token \
#   --from-literal=token=YOUR_TOKEN_HERE \
#   -n protodiff-system
#
# Then patch the deployment:
#
# kubectl patch deployment protodiff -n protodiff-system --patch '
# spec:
#   template:
#     spec:
#       containers:
#       - name: protodiff
#         env:
#         - name: BSR_TOKEN
#           valueFrom:
#             secretKeyRef:
#               name: bsr-token
#               key: token
# '
