# Example: Sample gRPC services that work with ProtoDiff
# This example shows complete deployment of two test gRPC servers (Go and Java)

---
# Namespace for test services
apiVersion: v1
kind: Namespace
metadata:
  name: grpc-test

---
# Go gRPC Server - Greeter Service
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-go
  namespace: grpc-test
  labels:
    app: grpc-server-go
spec:
  type: ClusterIP
  selector:
    app: grpc-server-go
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: grpc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-go
  namespace: grpc-test
  labels:
    app: grpc-server-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server-go
  template:
    metadata:
      labels:
        app: grpc-server-go
    spec:
      containers:
      - name: server
        image: wooojin2da/grpc-server-go:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
          name: grpc
          protocol: TCP
        env:
        - name: PORT
          value: "9090"
        - name: USER_SERVICE_ADDR
          value: "grpc-server-java.grpc-test.svc.cluster.local:9091"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 5

---
# Java gRPC Server - User Service
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-java
  namespace: grpc-test
  labels:
    app: grpc-server-java
spec:
  type: ClusterIP
  selector:
    app: grpc-server-java
  ports:
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: grpc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-java
  namespace: grpc-test
  labels:
    app: grpc-server-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server-java
  template:
    metadata:
      labels:
        app: grpc-server-java
    spec:
      containers:
      - name: server
        image: wooojin2da/grpc-server-java:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9091
          name: grpc
          protocol: TCP
        env:
        - name: PORT
          value: "9091"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 9091
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9091
          initialDelaySeconds: 5
          periodSeconds: 5

---
# Usage Instructions:
#
# See SAMPLE_QUICKSTART.md for detailed instructions in English and Korean
#
# Quick start:
# 1. Deploy services:
#    kubectl apply -f sample-grpc-service.yaml
#
# 2. Verify pods are running:
#    kubectl get pods -n grpc-test
#
# 3. Test inter-service communication:
#    kubectl port-forward -n grpc-test svc/grpc-server-go 9090:9090
#    grpcurl -plaintext -d '{"user_id": 1}' localhost:9090 greeter.Greeter/SayHelloToUser
#
# Notes:
# - Both servers have gRPC reflection enabled (required for ProtoDiff)
# - Services are discovered via ConfigMap in ProtoDiff install.yaml
# - Go Greeter service (port 9090) calls Java UserService (port 9091)
# - Images are pulled from Docker Hub: wooojin2da/grpc-server-*
